title: Mon site GitHub Pages
description: Un site statique avec Jekyll
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Pour GitHub Pages
baseurl: "/gis_starter_jekyll_geolab" # ou "/nom-du-repo" si nécessaire
url: "https://voirinprof.github.io"
